name: Assign

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  assign:
    name: Assign yourself
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub assignees
        run: gh pr edit ${{ github.event.number }} --add-assignee hirotomoyamada --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
