name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Time
        run: |
          echo $(date -d '+9 hours -1 day' '+%Y-%m-%d %H:%M:%S')

      # - name: Update README
      #   run: |
      #     echo "This is updated." > README.md

      # - name: Create PR
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.BOT_TOKEN }}
      #     base: main
      #     commit-message: 'ci(changesets): version packages'
      #     title: 'Updated documentation'
      #     branch: release
      #     assignees: 'hirotomoyamada'
      #     reviewers: 'hirotomoyamada'
