name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Check modified files
      #   id: check-modified
      #   uses: ./.github/composite-actions/check-modified-files
      #   with:
      #     files: |
      #       packages/(?!c/).*/README.md

      - name: Get all changed markdown files
        id: check-modified
        uses: tj-actions/changed-files@v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            packages/**/README.md
            !packages/b/**

      - name: Run
        if: steps.check-modified.outputs.any_changed == 'true'
        run: |
          echo "changed"
