name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          files: |
            .github/
            text.md

      - name: Run
        if: steps.check-modified.outputs.changed == 'true'
        run: |
          echo "changed: ${{ steps.check-modified.outputs.modified_files }}"
